oftoledo/art/models.py
from oftoledo.database import Column, Model, SurrogatePK, db, reference_col, relationship

class Portfolio(SurrogatePK, Model):
    """A portfolio for a user."""

    __tablename__ = 'portfolios'
    title = Column(db.String(80), nullable=True)
    description = Column(db.String(), nullable=True)
    cover_image = Column(db.String(80), nullable=True)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='portfolios')

    def __init__(self, **kwargs):
        """Create instance."""
        db.Model.__init__(self, **kwargs)

class Art(SurrogatePK, Model):
    """Art in a users portfolio."""

    __tablename__ = 'arts'
    title = Column(db.String(80), nullable=True)
    description = Column(db.String(), nullable=True)
    image = Column(db.String(), nullable=False)
    portfolio_id = reference_col('portfolios', nullable=True)
    portfolio = relationship('Portfolio', backref='arts')

    def __init__(self, **kwargs):
        """Create instance."""
        db.Model.__init__(self, **kwargs)

oftoledo/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin
from oftoledo.database import Column, Model, SurrogatePK, db, reference_col, relationship
from oftoledo.extensions import bcrypt

class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    email = Column(db.String(80), unique=True, nullable=False)
    username = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    full_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    confirmed = Column(db.Boolean(), default=False, nullable=False)

    def __init__(self, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    # Uncomment this if you opt to have a user give a first and last name seperately
    # @property
    # def full_name(self):
    #     """Full user name."""
    #     return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({email!r})>'.format(email=self.email)

oftoledo/art/forms.py
# -*- coding: utf-8 -*-
"""Art forms."""
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

from .models import Portfolio, Art

class PortfolioForm(Form):
    """Portfolio form."""
    title = StringField('Portfolio Title', validators=[DataRequired()])
    description = StringField('Description')
    submit = SubmitField("Make new portfolio")

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(PortfolioForm, self).__init__(*args, **kwargs)
        self.portfolio = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(PortfolioForm, self).validate()
        if not initial_validation:
            return False

        return True

oftoledo/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form, RecaptchaField
from wtforms import PasswordField, StringField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class UpdateInfo(Form):
    """ Let a User update their info"""
    full_name = StringField('Full Name',
        validators=[DataRequired(), Length(max=50)])  
    isNewsletter = BooleanField('Do you want to sign up for our newsletter?')
    submit = SubmitField("Update Info")

class RegisterForm(Form):
    """Register form."""
    recaptcha = RecaptchaField()
    full_name = StringField('Full Name',
        validators=[DataRequired(), Length(min=2, max=25)])
    email = StringField('Email',
        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    username = StringField('Username',
        validators=[DataRequired(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False

        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already taken')
            return False

        return True

oftoledo/__init__.py
"""Main application package."""

oftoledo/admin/__init__.py
# -*- coding: utf-8 -*-
"""The admin module, to control admin facing functionality"""
from . import views  # noqa

oftoledo/admin/views.py
# -*- coding: utf-8 -*-
"""Admin views."""
from flask import Blueprint, render_template
from flask_login import login_required
from oftoledo.decorators import check_admin
from oftoledo.user.models import User

blueprint = Blueprint('admin', __name__, url_prefix='/admin', static_folder='../static')

# =================================
# 			ADMIN ROUTES
# =================================

@blueprint.route('/')
@login_required
@check_admin
def adminhome():
	"""Admin Home"""
	return render_template('admins/home.html')

@blueprint.route('/user/<int:user_id>/')
@login_required
@check_admin
def viewCustomer(user_id):
	"""View a Users Account"""
	user = User.query.filter_by(id = user_id).first()
	return render_template('admins/user.html', user = user)

oftoledo/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template

from oftoledo import public, user, admin, art
from oftoledo.assets import assets
from oftoledo.extensions import bcrypt, cache, csrf_protect, db, debug_toolbar, login_manager, migrate, mail
from oftoledo.settings import ProdConfig


def create_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(admin.views.blueprint)
    app.register_blueprint(art.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

oftoledo/art/__init__.py
"""The art module"""
from . import views 

oftoledo/art/views.py
# -*- coding: utf-8 -*-
"""Art views."""
from flask import Blueprint, render_template, redirect, url_for, flash, request, abort
from flask_login import login_required, current_user, logout_user 
from oftoledo.database import db
from oftoledo.art.forms import PortfolioForm
from oftoledo.art.models import Portfolio
from oftoledo.user.models import User

# If you need a user confirmed before completing an action
# from oftoledo.decorators import check_confirmed

blueprint = Blueprint('art', __name__, static_folder='../static')


@blueprint.route('/<username>', methods = ['GET', 'POST'])
def viewUser(username):
	user = User.query.filter_by(username = username).first()
	"""Abort if user not found"""
	if not user:
		return abort(404)
	portfolios = Portfolio.query.filter_by(user_id = user.id).all()
	return render_template('art/user.html', user = user, portfolios = portfolios)


# =================================
# 			PORTFOLIO ROUTES
# =================================

@blueprint.route('/newportfolio', methods = ['GET', 'POST'])
@login_required
def newPortfolio():
	"""Make a new portfolio"""
	form = PortfolioForm()
	if request.method == 'POST':
		if form.validate() == False:
			flash('Error. Pleae try again', 'danger')
			return redirect(url_for('art.newPortfolio'))
		else:
			"""Create Portfolio if form is valid"""
			Portfolio.create(title=form.title.data,
				description=form.description.data,
				user_id = current_user.id)
			flash('New Portfolio Made', 'success')
			return redirect(url_for('art.viewUser'))
	return render_template('art/newportfolio.html', form = form)

oftoledo/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

oftoledo/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user, logout_user 
from oftoledo.database import db
from oftoledo.user.forms import UpdateInfo
from oftoledo.send_emails import send_confirm_email

# If you need a user confirmed before completing an action
# from oftoledo.decorators import check_confirmed

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

# =================================
# 			USER ROUTES
# =================================

@blueprint.route('/logout/')
@login_required
def logout():
    """Logout."""
    logout_user()
    flash('You are logged out.', 'info')
    return redirect(url_for('public.home'))

@blueprint.route('/updateaccount', methods = ['POST'])
@login_required
def updateAccount():
	"""List members."""
	form = UpdateInfo()
	if request.method == 'POST':
	    if form.validate() == False:
	    	flash('Error. Pleae try again', 'danger')
	        return redirect(url_for('user.account'))
	    else:
	    	user = current_user
	    	user.full_name = form.full_name.data
	    	db.session.add(user)
	    	db.session.commit()
	        flash('Account Information Updated', 'success')
	        return redirect(url_for('user.account'))

@blueprint.route('/my-account')
@login_required
def account():
	"""Show User Account Page."""
	form = UpdateInfo()
	return render_template('users/account.html', form = form)

@blueprint.route('/re-confirm/', methods = ['POST'])
@login_required
def reconfirmEmail():
    """Send user another confirm email if they didn't get the first"""
    user = current_user
    send_confirm_email(user)
    flash('Thank you, please check your email.', 'success')
    return redirect(url_for('public.home'))

oftoledo/templates/401.html
{% extends "userlayout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

oftoledo/templates/adminlayout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block metaTitle %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/admin.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('user.adminhome') }}">
                    <img src="http://placehold.it/100x50">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('public.home') }}">Exit Admin</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}


    <!-- Page Content -->
   {% block body %}
   {% endblock %}


    <!-- Footer -->
    <footer class="footer">
        <p>Admin Footer Here</p>
    </footer>



    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>

</html>

oftoledo/templates/emaillayout.html
<!DOCTYPE html>
<html style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>{% block title %}{% endblock %}</title>
</head>
<body bgcolor="#f6f6f6" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; -webkit-font-smoothing: antialiased; height: 100%; -webkit-text-size-adjust: none; width: 100% !important; margin: 0; padding: 0;">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; width: 100%; margin: 0; padding: 20px;"><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;"></td>
    <td class="container" bgcolor="#FFFFFF" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; clear: both !important; display: block !important; max-width: 600px !important; Margin: 0 auto; padding: 20px; border: 1px solid #f0f0f0;">

      <!-- content -->

      

      <div class="content" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; display: block; max-width: 600px; margin: 0 auto; padding: 0;">
      <table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; width: 100%; margin: 0; padding: 0;"><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
            {% block body %}
      {% endblock %}
            
          </td>
        </tr></table>
</div>
      <!-- /content -->
      
    </td>
    <td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;"></td>
  </tr></table>
<!-- /body --><!-- footer --><table class="footer-wrap" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; clear: both !important; width: 100%; margin: 0; padding: 0;"><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;"></td>
    <td class="container" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; clear: both !important; display: block !important; max-width: 600px !important; margin: 0 auto; padding: 0;">
      
      <!-- content -->

      <div class="content" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; display: block; max-width: 600px; margin: 0 auto; padding: 0;">
        <table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; width: 100%; margin: 0; padding: 0;"><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<td align="center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
            </td>
          </tr></table>
</div>
      <!-- /content -->
      
    </td>
    <td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;"></td>
  </tr></table>
<!-- /footer -->
</body>
</html>

oftoledo/templates/userlayout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="{% block metaDescription %}{% endblock %}">
    <meta name="keywords" content="{% block metaKeywords %}{% endblock %}">

    <title>{% block metaTitle %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('public.home') }}">
                    <img src="http://placehold.it/100x50">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    
                    {% if current_user and current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for('art.newPortfolio') }}">New Portfolio</a>
                    </li>
                    <li>
                        <a href="{{ url_for('user.account') }}">My Account</a>
                    </li>
                    <li>
                        <a href="{{ url_for('user.logout') }}">Logout</a>
                    </li>

                    {% else %}
                    <li>
                        <a href="{{ url_for('public.about') }}">About</a>
                    </li>
                    <li>
                        <a href="{{ url_for('public.contact') }}">Contact</a>
                    </li>
                    <li>
                        <a href="{{ url_for('public.register') }}">Create Account</a>
                    </li>
                    <li>
                        <a href="{{ url_for('public.login_page') }}">Login</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    <!-- Page Content -->
   {% block body %}
   {% endblock %}

    <footer>
        <ul class="nav navbar-nav">
            <li>
                <a href="{{ url_for('public.about') }}">About</a>
            </li>
            <li>
                <a href="{{ url_for('public.contact') }}">Contact</a>
            </li>
            <li>
            
                <a>Copyright &copy; ofToledo, 2016</a>
            </li>
        </ul>
    </footer>

    

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>

</html>